#! /usr/bin/env ruby

require 'optparse'
require 'pry'

lib = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'csvsql'

result = Csvsql::CommandRunner.run!(ARGV)
puts result if result
